static glClearIndex               := { arg_types: ["float"] }
static glClearColor               := { arg_types: ["float", "float", "float", "float"] }
static glClear                    := { arg_types: ["uint"] }
static glIndexMask                := { arg_types: ["uint"] }
static glColorMask                := { arg_types: ["uchar", "uchar", "uchar", "uchar"] }
static glAlphaFunc                := { arg_types: ["uint", "float"] }
static glBlendFunc                := { arg_types: ["uint", "uint"] }
static glLogicOp                  := { arg_types: ["uint"] }
static glCullFace                 := { arg_types: ["uint"] }
static glFrontFace                := { arg_types: ["uint"] }
static glPointSize                := { arg_types: ["float"] }
static glLineWidth                := { arg_types: ["float"] }
static glLineStipple              := { arg_types: ["int", "ushort"] }
static glPolygonMode              := { arg_types: ["uint", "uint"] }
static glPolygonOffset            := { arg_types: ["float", "float"] }
static glPolygonStipple           := { arg_types: ["uchar*"] }
static glGetPolygonStipple        := { arg_types: ["uchar*"] }
static glEdgeFlag                 := { arg_types: ["uchar"] }
static glEdgeFlagv                := { arg_types: ["uchar*"] }
static glScissor                  := { arg_types: ["int", "int", "int", "int"] }
static glClipPlane                := { arg_types: ["uint", "double*"] }
static glGetClipPlane             := { arg_types: ["uint", "double*"] }
static glDrawBuffer               := { arg_types: ["uint"] }
static glReadBuffer               := { arg_types: ["uint"] }
static glEnable                   := { arg_types: ["uint"] }
static glDisable                  := { arg_types: ["uint"] }
static glIsEnabled                := { arg_types: ["uint"] }
static glEnableClientState        := { arg_types: ["uint"] }  
static glDisableClientState       := { arg_types: ["uint"] }  
static glGetBooleanv              := { arg_types: ["uint", "uchar*"] }
static glGetDoublev               := { arg_types: ["uint", "double*"] }
static glGetFloatv                := { arg_types: ["uint", "float*"] }
static glGetIntegerv              := { arg_types: ["uint", "int*"] }
static glPushAttrib               := { arg_types: ["uint"] }
static glPopAttrib                := { arg_types: [] }
static glPushClientAttrib         := { arg_types: ["uint"] }  
static glPopClientAttrib          := { arg_types: [] }  
static glRenderMode               := { arg_types: ["uint"] }
static uint glGetError            := { arg_types: [] }
static glGetString                := { arg_types: ["uint"] }
static glFinish                   := { arg_types: [] }
static glFlush                    := { arg_types: [] }
static glHint                     := { arg_types: ["uint", "uint"] }
static glClearDepth               := { arg_types: ["double"] }
static glDepthFunc                := { arg_types: ["uint"] }
static glDepthMask                := { arg_types: ["uchar"] }
static glDepthRange               := { arg_types: ["double", "double"] }
static glClearAccum               := { arg_types: ["float", "float", "float", "float"] }
static glAccum                    := { arg_types: ["uint", "float"] }
static glMatrixMode               := { arg_types: ["uint"] }
static glOrtho                    := { arg_types: ["double", "double", "double", "double", "double", "double"] }
static glFrustum                  := { arg_types: ["double", "double", "double", "double", "double", "double"] }
static glViewport                 := { arg_types: ["int", "int", "int", "int"] }
static glPushMatrix               := { arg_types: [] }
static glPopMatrix                := { arg_types: [] }
static glLoadIdentity             := { arg_types: [] }
static glLoadMatrixd              := { arg_types: ["double*"] }
static glLoadMatrixf              := { arg_types: ["float*"] }
static glMultMatrixd              := { arg_types: ["double*"] }
static glMultMatrixf              := { arg_types: ["float*"] }
static glRotated                  := { arg_types: ["double", "double", "double", "double"] }
static glRotatef                  := { arg_types: ["float", "float", "float", "float"] }
static glScaled                   := { arg_types: ["double", "double", "double"] }
static glScalef                   := { arg_types: ["float", "float", "float"] }
static glTranslated               := { arg_types: ["double", "double", "double"] }
static glTranslatef               := { arg_types: ["float", "float", "float"] }
static uchar glIsList             := { arg_types: ["uint"] }
static glDeleteLists              := { arg_types: ["uint", "int"] }
static uint glGenLists            := { arg_types: ["int"] }
static glNewList                  := { arg_types: ["uint", "uint"] }
static glEndList                  := { arg_types: [] }
static glCallList                 := { arg_types: ["uint"] }
static glCallLists                := { arg_types: ["int", "uint", "*lists"] }
static glListBase                 := { arg_types: ["uint"] }
static glBegin                    := { arg_types: ["uint"] }
static glEnd                      := { arg_types: [] }
static glVertex2d                 := { arg_types: ["double", "double"] }
static glVertex2f                 := { arg_types: ["float", "float"] }
static glVertex2i                 := { arg_types: ["int", "int"] }
static glVertex2s                 := { arg_types: ["short", "short"] }
static glVertex3d                 := { arg_types: ["double", "double", "double"] }
static glVertex3f                 := { arg_types: ["float", "float", "float"] }
static glVertex3i                 := { arg_types: ["int", "int", "int"] }
static glVertex3s                 := { arg_types: ["short", "short", "short"] }
static glVertex4d                 := { arg_types: ["double", "double", "double", "double"] }
static glVertex4f                 := { arg_types: ["float", "float", "float", "float"] }
static glVertex4i                 := { arg_types: ["int", "int", "int", "int"] }
static glVertex4s                 := { arg_types: ["short", "short", "short", "short"] }
static glVertex2dv                := { arg_types: ["double*"] }
static glVertex2fv                := { arg_types: ["float*"] }
static glVertex2iv                := { arg_types: ["int*"] }
static glVertex2sv                := { arg_types: ["short*"] }
static glVertex3dv                := { arg_types: ["double*"] }
static glVertex3fv                := { arg_types: ["float*"] }
static glVertex3iv                := { arg_types: ["int*"] }
static glVertex3sv                := { arg_types: ["short*"] }
static glVertex4dv                := { arg_types: ["double*"] }
static glVertex4fv                := { arg_types: ["float*"] }
static glVertex4iv                := { arg_types: ["int*"] }
static glVertex4sv                := { arg_types: ["short*"] }
static glNormal3b                 := { arg_types: ["char", "char", "char"] }
static glNormal3d                 := { arg_types: ["double", "double", "double"] }
static glNormal3f                 := { arg_types: ["float", "float", "float"] }
static glNormal3i                 := { arg_types: ["int", "int", "int"] }
static glNormal3s                 := { arg_types: ["short", "short", "short"] }
static glNormal3bv                := { arg_types: ["char*"] }
static glNormal3dv                := { arg_types: ["double*"] }
static glNormal3fv                := { arg_types: ["float*"] }
static glNormal3iv                := { arg_types: ["int*"] }
static glNormal3sv                := { arg_types: ["short*"] }
static glIndexd                   := { arg_types: ["double"] }
static glIndexf                   := { arg_types: ["float"] }
static glIndexi                   := { arg_types: ["int"] }
static glIndexs                   := { arg_types: ["short"] }
static glIndexub                  := { arg_types: ["uchar"] }  
static glIndexdv                  := { arg_types: ["double*"] }
static glIndexfv                  := { arg_types: ["float*"] }
static glIndexiv                  := { arg_types: ["int*"] }
static glIndexsv                  := { arg_types: ["short*"] }
static glIndexubv                 := { arg_types: ["uchar*"] }  
static glColor3b                  := { arg_types: ["char", "char", "char"] }
static glColor3d                  := { arg_types: ["double", "double", "double"] }
static glColor3f                  := { arg_types: ["float", "float", "float"] }
static glColor3i                  := { arg_types: ["int", "int", "int"] }
static glColor3s                  := { arg_types: ["short", "short", "short"] }
static glColor3ub                 := { arg_types: ["uchar", "uchar", "uchar"] }
static glColor3ui                 := { arg_types: ["uint", "uint", "uint"] }
static glColor3us                 := { arg_types: ["ushort", "ushort", "ushort"] }
static glColor4b                  := { arg_types: ["char", "char", "char", "char"] }
static glColor4d                  := { arg_types: ["double", "double", "double", "double"] }
static glColor4f                  := { arg_types: ["float", "float", "float", "float"] }
static glColor4i                  := { arg_types: ["int", "int", "int", "int"] }
static glColor4s                  := { arg_types: ["short", "short", "short", "short"] }
static glColor4ub                 := { arg_types: ["uchar", "uchar", "uchar", "uchar"] }
static glColor4ui                 := { arg_types: ["uint", "uint", "uint", "uint"] }
static glColor4us                 := { arg_types: ["ushort", "ushort", "ushort", "ushort"] }
static glColor3bv                 := { arg_types: ["char*"] }
static glColor3dv                 := { arg_types: ["double*"] }
static glColor3fv                 := { arg_types: ["float*"] }
static glColor3iv                 := { arg_types: ["int*"] }
static glColor3sv                 := { arg_types: ["short*"] }
static glColor3ubv                := { arg_types: ["uchar*"] }
static glColor3uiv                := { arg_types: ["uint*"] }
static glColor3usv                := { arg_types: ["ushort*"] }
static glColor4bv                 := { arg_types: ["char*"] }
static glColor4dv                 := { arg_types: ["double*"] }
static glColor4fv                 := { arg_types: ["float*"] }
static glColor4iv                 := { arg_types: ["int*"] }
static glColor4sv                 := { arg_types: ["short*"] }
static glColor4ubv                := { arg_types: ["uchar*"] }
static glColor4uiv                := { arg_types: ["uint*"] }
static glColor4usv                := { arg_types: ["ushort*"] }
static glTexCoord1d               := { arg_types: ["double"] }
static glTexCoord1f               := { arg_types: ["float"] }
static glTexCoord1i               := { arg_types: ["int"] }
static glTexCoord1s               := { arg_types: ["short"] }
static glTexCoord2d               := { arg_types: ["double", "double"] }
static glTexCoord2f               := { arg_types: ["float", "float"] }
static glTexCoord2i               := { arg_types: ["int", "int"] }
static glTexCoord2s               := { arg_types: ["short", "short"] }
static glTexCoord3d               := { arg_types: ["double", "double", "double"] }
static glTexCoord3f               := { arg_types: ["float", "float", "float"] }
static glTexCoord3i               := { arg_types: ["int", "int", "int"] }
static glTexCoord3s               := { arg_types: ["short", "short", "short"] }
static glTexCoord4d               := { arg_types: ["double", "double", "double", "double"] }
static glTexCoord4f               := { arg_types: ["float", "float", "float", "float"] }
static glTexCoord4i               := { arg_types: ["int", "int", "int", "int"] }
static glTexCoord4s               := { arg_types: ["short", "short", "short", "short"] }
static glTexCoord1dv              := { arg_types: ["double*"] }
static glTexCoord1fv              := { arg_types: ["float*"] }
static glTexCoord1iv              := { arg_types: ["int*"] }
static glTexCoord1sv              := { arg_types: ["short*"] }
static glTexCoord2dv              := { arg_types: ["double*"] }
static glTexCoord2fv              := { arg_types: ["float*"] }
static glTexCoord2iv              := { arg_types: ["int*"] }
static glTexCoord2sv              := { arg_types: ["short*"] }
static glTexCoord3dv              := { arg_types: ["double*"] }
static glTexCoord3fv              := { arg_types: ["float*"] }
static glTexCoord3iv              := { arg_types: ["int*"] }
static glTexCoord3sv              := { arg_types: ["short*"] }
static glTexCoord4dv              := { arg_types: ["double*"] }
static glTexCoord4fv              := { arg_types: ["float*"] }
static glTexCoord4iv              := { arg_types: ["int*"] }
static glTexCoord4sv              := { arg_types: ["short*"] }
static glRasterPos2d              := { arg_types: ["double", "double"] }
static glRasterPos2f              := { arg_types: ["float", "float"] }
static glRasterPos2i              := { arg_types: ["int", "int"] }
static glRasterPos2s              := { arg_types: ["short", "short"] }
static glRasterPos3d              := { arg_types: ["double", "double", "double"] }
static glRasterPos3f              := { arg_types: ["float", "float", "float"] }
static glRasterPos3i              := { arg_types: ["int", "int", "int"] }
static glRasterPos3s              := { arg_types: ["short", "short", "short"] }
static glRasterPos4d              := { arg_types: ["double", "double", "double", "double"] }
static glRasterPos4f              := { arg_types: ["float", "float", "float", "float"] }
static glRasterPos4i              := { arg_types: ["int", "int", "int", "int"] }
static glRasterPos4s              := { arg_types: ["short", "short", "short", "short"] }
static glRasterPos2dv             := { arg_types: ["double*"] }
static glRasterPos2fv             := { arg_types: ["float*"] }
static glRasterPos2iv             := { arg_types: ["int*"] }
static glRasterPos2sv             := { arg_types: ["short*"] }
static glRasterPos3dv             := { arg_types: ["double*"] }
static glRasterPos3fv             := { arg_types: ["float*"] }
static glRasterPos3iv             := { arg_types: ["int*"] }
static glRasterPos3sv             := { arg_types: ["short*"] }
static glRasterPos4dv             := { arg_types: ["double*"] }
static glRasterPos4fv             := { arg_types: ["float*"] }
static glRasterPos4iv             := { arg_types: ["int*"] }
static glRasterPos4sv             := { arg_types: ["short*"] }
static glRectd                    := { arg_types: ["double", "double", "double", "double"] }
static glRectf                    := { arg_types: ["float", "float", "float", "float"] }
static glRecti                    := { arg_types: ["int", "int", "int", "int"] }
static glRects                    := { arg_types: ["short", "short", "short", "short"] }
static glRectdv                   := { arg_types: ["double*", "double*"] }
static glRectfv                   := { arg_types: ["float*", "float*"] }
static glRectiv                   := { arg_types: ["int*", "int*"] }
static glRectsv                   := { arg_types: ["short*", "short*"] }
static glShadeModel               := { arg_types: ["uint"] }
static glLightf                   := { arg_types: ["uint", "uint", "float"] }
static glLighti                   := { arg_types: ["uint", "uint", "int"] }
static glLightfv                  := { arg_types: ["uint", "uint", "float*"] }
static glLightiv                  := { arg_types: ["uint", "uint", "int*"] }
static glGetLightfv               := { arg_types: ["uint", "uint", "float*"] }
static glGetLightiv               := { arg_types: ["uint", "uint", "int*"] }
static glLightModelf              := { arg_types: ["uint", "float"] }
static glLightModeli              := { arg_types: ["uint", "int"] }
static glLightModelfv             := { arg_types: ["uint", "float*"] }
static glLightModeliv             := { arg_types: ["uint", "int*"] }
static glMaterialf                := { arg_types: ["uint", "uint", "float"] }
static glMateriali                := { arg_types: ["uint", "uint", "int"] }
static glMaterialfv               := { arg_types: ["uint", "uint", "float*"] }
static glMaterialiv               := { arg_types: ["uint", "uint", "int*"] }
static glGetMaterialfv            := { arg_types: ["uint", "uint", "float*"] }
static glGetMaterialiv            := { arg_types: ["uint", "uint", "int*"] }
static glColorMaterial            := { arg_types: ["uint", "uint"] }
static glPixelZoom                := { arg_types: ["float", "float"] }
static glPixelStoref              := { arg_types: ["uint", "float"] }
static glPixelStorei              := { arg_types: ["uint", "int"] }
static glPixelTransferf           := { arg_types: ["uint", "float"] }
static glPixelTransferi           := { arg_types: ["uint", "int"] }
static glPixelMapfv               := { arg_types: ["uint", "int", "float*"] }
static glPixelMapuiv              := { arg_types: ["uint", "int", "uint*"] }
static glPixelMapusv              := { arg_types: ["uint", "int", "ushort*"] }
static glGetPixelMapfv            := { arg_types: ["uint", "float*"] }
static glGetPixelMapuiv           := { arg_types: ["uint", "uint*"] }
static glGetPixelMapusv           := { arg_types: ["uint", "ushort*"] }
static glBitmap                   := { arg_types: ["int", "int", "float", "float", "float", "float", "uchar*"] }
static glReadPixels               := { arg_types: ["int", "int", "int", "int", "uint", "uint ", "*pixels"] }
static glDrawPixels               := { arg_types: ["int", "int", "uint", "uint", "*pixels"] }
static glCopyPixels               := { arg_types: ["int", "int", "int", "int", "uint"] }
static glStencilFunc              := { arg_types: ["uint", "int", "uint"] }
static glStencilMask              := { arg_types: ["uint"] }
static glStencilOp                := { arg_types: ["uint", "uint", "uint"] }
static glClearStencil             := { arg_types: ["int"] }
static glTexGend                  := { arg_types: ["uint", "uint", "double"] }
static glTexGenf                  := { arg_types: ["uint", "uint", "float"] }
static glTexGeni                  := { arg_types: ["uint", "uint", "int"] }
static glTexGendv                 := { arg_types: ["uint", "uint", "double*"] }
static glTexGenfv                 := { arg_types: ["uint", "uint", "float*"] }
static glTexGeniv                 := { arg_types: ["uint", "uint", "int*"] }
static glGetTexGendv              := { arg_types: ["uint", "uint", "double*"] }
static glGetTexGenfv              := { arg_types: ["uint", "uint", "float*"] }
static glGetTexGeniv              := { arg_types: ["uint", "uint", "int*"] }
static glTexEnvf                  := { arg_types: ["uint", "uint", "float"] }
static glTexEnvi                  := { arg_types: ["uint", "uint", "int"] }
static glTexEnvfv                 := { arg_types: ["uint", "uint", "float*"] }
static glTexEnviv                 := { arg_types: ["uint", "uint", "int*"] }
static glGetTexEnvfv              := { arg_types: ["uint", "uint", "float*"] }
static glGetTexEnviv              := { arg_types: ["uint", "uint", "int*"] }
static glTexParameterf            := { arg_types: ["uint", "uint", "float"] }
static glTexParameteri            := { arg_types: ["uint", "uint", "int"] }
static glTexParameterfv           := { arg_types: ["uint", "uint", "float*"] }
static glTexParameteriv           := { arg_types: ["uint", "uint", "int*"] }
static glGetTexParameterfv        := { arg_types: ["uint", "uint", "float*"] }
static glGetTexParameteriv        := { arg_types: ["uint", "uint", "int*"] }
static glGetTexLevelParameterfv   := { arg_types: ["uint", "int", "uint", "float*"] }
static glGetTexLevelParameteriv   := { arg_types: ["uint", "int", "uint", "int*"] }
static glTexImage1D               := { arg_types: ["uint", "int", "int", "int", "int", "uint", "uint", "*pixels"] }
static glTexImage2D               := { arg_types: ["uint", "int", "int", "int", "int", "int", "uint", "uint", "*pixels"] }
static glGetTexImage              := { arg_types: ["uint", "int", "uint", "uint ", "*pixels"] }
static glMap1d                    := { arg_types: ["uint", "double", "double", "int", "int", "double*"] }
static glMap1f                    := { arg_types: ["uint", "float", "float", "int", "int", "float*"] }
static glMap2d                    := { arg_types: ["uint", "double", "double", "int", "int", "double", "double", "int", "int", "double*"] }
static glMap2f                    := { arg_types: ["uint", "float", "float", "int", "int", "float", "float", "int", "int", "float*"] }
static glGetMapdv                 := { arg_types: ["uint", "uint", "double*"] }
static glGetMapfv                 := { arg_types: ["uint", "uint", "float*"] }
static glGetMapiv                 := { arg_types: ["uint", "uint", "int*"] }
static glEvalCoord1d              := { arg_types: ["double"] }
static glEvalCoord1f              := { arg_types: ["float"] }
static glEvalCoord1dv             := { arg_types: ["double*"] }
static glEvalCoord1fv             := { arg_types: ["float*"] }
static glEvalCoord2d              := { arg_types: ["double", "double"] }
static glEvalCoord2f              := { arg_types: ["float", "float"] }
static glEvalCoord2dv             := { arg_types: ["double*"] }
static glEvalCoord2fv             := { arg_types: ["float*"] }
static glMapGrid1d                := { arg_types: ["int", "double", "double"] }
static glMapGrid1f                := { arg_types: ["int", "float", "float"] }
static glMapGrid2d                := { arg_types: ["int", "double", "double", "int", "double", "double"] }
static glMapGrid2f                := { arg_types: ["int", "float", "float", "int", "float", "float"] }
static glEvalPoint1               := { arg_types: ["int"] }
static glEvalPoint2               := { arg_types: ["int", "int"] }
static glEvalMesh1                := { arg_types: ["uint", "int", "int"] }
static glEvalMesh2                := { arg_types: ["uint", "int", "int", "int", "int"] }
static glFogf                     := { arg_types: ["uint", "float"] }
static glFogi                     := { arg_types: ["uint", "int"] }
static glFogfv                    := { arg_types: ["uint", "float*"] }
static glFogiv                    := { arg_types: ["uint", "int*"] }
static glFeedbackBuffer           := { arg_types: ["int", "uint", "float*"] }
static glPassThrough              := { arg_types: ["float"] }
static glSelectBuffer             := { arg_types: ["int", "uint*"] }
static glInitNames                := { arg_types: [] }
static glLoadName                 := { arg_types: ["uint"] }
static glPushName                 := { arg_types: ["uint"] }
static glPopName                  := { arg_types: [] }
static glGenTextures              := { arg_types: ["int", "uint*"] }
static glDeleteTextures           := { arg_types: ["int", "uint*"] }
static glBindTexture              := { arg_types: ["uint", "uint"] }
static glPrioritizeTextures       := { arg_types: ["int", "uint*", "float*"] }
static uchar glAreTexturesResident:= { arg_types: ["int", "uint*", "uchar*"] }
static uchar glIsTexture          := { arg_types: ["uint"] }
static glTexSubImage1D            := { arg_types: ["uint", "int", "int", "int", "uint", "uint", "*pixels"] }
static glTexSubImage2D            := { arg_types: ["uint", "int", "int", "int", "int", "int", "uint", "uint", "*pixels"] }
static glCopyTexImage1D           := { arg_types: ["uint", "int", "uint", "int", "int", "int", "int"] }
static glCopyTexImage2D           := { arg_types: ["uint", "int", "uint", "int", "int", "int", "int", "int"] }
static glCopyTexSubImage1D        := { arg_types: ["uint", "int", "int", "int", "int", "int"] }
static glCopyTexSubImage2D        := { arg_types: ["uint", "int", "int", "int", "int", "int", "int", "int"] }
static glVertexPointer            := { arg_types: ["int", "uint", "int", "*ptr"] }
static glNormalPointer            := { arg_types: ["uint", "int", "*ptr"] }
static glColorPointer             := { arg_types: ["int", "uint", "int", "*ptr"] }
static glIndexPointer             := { arg_types: ["uint", "int", "*ptr"] }
static glTexCoordPointer          := { arg_types: ["int", "uint", "int", "*ptr"] }
static glEdgeFlagPointer          := { arg_types: ["int", "*ptr"] }
static glGetPointerv              := { arg_types: ["uint ", "**params"] }
static glArrayElement             := { arg_types: ["int"] }
static glDrawArrays               := { arg_types: ["uint", "int", "int"] }
static glDrawElements             := { arg_types: ["uint", "int", "uint", "*indices"] }
static interleavedArrays          := { arg_types: ["uint", "int", "*pointer"] }
static glDrawRangeElements        := { arg_types: ["uint", "uint", "uint", "int", "uint", "*indices"] }
static glTexImage3D               := { arg_types: ["uint", "int", "uint", "int", "int", "int", "int", "uint", "uint", "*pixels"] }
static glTexSubImage3D            := { arg_types: ["uint", "int", "int", "int", "int", "int", "int", "int", "uint", "uint", "*pixels"] }
static glCopyTexSubImage3D        := { arg_types: ["uint", "int", "int", "int", "int", "int", "int", "int", "int"] }
static glColorTable               := { arg_types: ["uint", "uint", "int", "uint", "uint", "*table"] }
static glColorSubTable            := { arg_types: ["uint", "int", "int", "uint", "uint", "*data"] }
static glColorTableParameteriv    := { arg_types: ["uint", "uint", "int*"] }
static glColorTableParameterfv    := { arg_types: ["uint", "uint", "float*"] }
static glCopyColorSubTable        := { arg_types: ["uint", "int", "int", "int", "int"] }
static glCopyColorTable           := { arg_types: ["uint", "uint", "int", "int", "int"] }
static glGetColorTable            := { arg_types: ["uint", "uint", "uint ", "*table"] }
static glGetColorTableParameterfv := { arg_types: ["uint", "uint", "float*"] }
static glGetColorTableParameteriv := { arg_types: ["uint", "uint", "int*"] }
static glBlendEquation            := { arg_types: ["uint"] }
static glBlendColor               := { arg_types: ["float", "float", "float", "float"] }
static glHistogram                := { arg_types: ["uint", "int", "uint", "uchar"] }
static glResetHistogram           := { arg_types: ["uint"] }
static glGetHistogram             := { arg_types: ["uint", "uchar", "uint", "uint ", "*values"] }
static glGetHistogramParameterfv  := { arg_types: ["uint", "uint", "float*"] }
static glGetHistogramParameteriv  := { arg_types: ["uint", "uint", "int*"] }
static glMinmax                   := { arg_types: ["uint", "uint", "uchar"] }
static glResetMinmax              := { arg_types: ["uint"] }
static glGetMinmax                := { arg_types: ["uint", "uchar", "uint", "uint ", "*values"] }
static glGetMinmaxParameterfv     := { arg_types: ["uint", "uint", "float*"] }
static glGetMinmaxParameteriv     := { arg_types: ["uint", "uint", "int*"] }
static glConvolutionFilter1D      := { arg_types: ["uint", "uint", "int", "uint", "uint", "*image"] }
static glConvolutionFilter2D      := { arg_types: ["uint", "uint", "int", "int", "uint", "uint", "*image"] }
static glConvolutionParameterf    := { arg_types: ["uint", "uint", "float"] }
static glConvolutionParameterfv   := { arg_types: ["uint", "uint", "float*"] }
static glConvolutionParameteri    := { arg_types: ["uint", "uint", "int"] }
static glConvolutionParameteriv   := { arg_types: ["uint", "uint", "int*"] }
static glCopyConvolutionFilter1D  := { arg_types: ["uint", "uint", "int", "int", "int"] }
static glCopyConvolutionFilter2D  := { arg_types: ["uint", "uint", "int", "int", "int", "int"] }
static glGetConvolutionFilter     := { arg_types: ["uint", "uint", "uint ", "*image"] }
static glGetConvolutionParameterfv:= { arg_types: ["uint", "uint", "float*"] }
static glGetConvolutionParameteriv:= { arg_types: ["uint", "uint", "int*"] }
static glSeparableFilter2D        := { arg_types: ["uint", "uint", "int", "int", "uint", "uint", "*row", "*column"] }
static glGetSeparableFilter       := { arg_types: ["uint", "uint", "uint ", "*row", "*column", "*span"] }
static glActiveTexture            := { arg_types: ["uint"] }
static glClientActiveTexture      := { arg_types: ["uint"] }
static glCompressedTexImage1D     := { arg_types: ["uint", "int", "uint", "int", "int", "int", "*data"] }
static glCompressedTexImage2D     := { arg_types: ["uint", "int", "uint", "int", "int", "int", "int", "*data"] }
static glCompressedTexImage3D     := { arg_types: ["uint", "int", "uint", "int", "int", "int", "int", "int", "*data"] }
static glCompressedTexSubImage1D  := { arg_types: ["uint", "int", "int", "int", "uint", "int", "*data"] }
static glCompressedTexSubImage2D  := { arg_types: ["uint", "int", "int", "int", "int", "int", "uint", "int", "*data"] }
static glCompressedTexSubImage3D  := { arg_types: ["uint", "int", "int", "int", "int", "int", "int", "int", "uint", "int", "*data"] }
static glGetCompressedTexImage    := { arg_types: ["uint", "int ", "*img"] }
static glMultiTexCoord1d          := { arg_types: ["uint", "double"] }
static glMultiTexCoord1dv         := { arg_types: ["uint", "double*"] }
static glMultiTexCoord1f          := { arg_types: ["uint", "float"] }
static glMultiTexCoord1fv         := { arg_types: ["uint", "float*"] }
static glMultiTexCoord1i          := { arg_types: ["uint", "int"] }
static glMultiTexCoord1iv         := { arg_types: ["uint", "int*"] }
static glMultiTexCoord1s          := { arg_types: ["uint", "short"] }
static glMultiTexCoord1sv         := { arg_types: ["uint", "short*"] }
static glMultiTexCoord2d          := { arg_types: ["uint", "double", "double"] }
static glMultiTexCoord2dv         := { arg_types: ["uint", "double*"] }
static glMultiTexCoord2f          := { arg_types: ["uint", "float", "float"] }
static glMultiTexCoord2fv         := { arg_types: ["uint", "float*"] }
static glMultiTexCoord2i          := { arg_types: ["uint", "int", "int"] }
static glMultiTexCoord2iv         := { arg_types: ["uint", "int*"] }
static glMultiTexCoord2s          := { arg_types: ["uint", "short", "short"] }
static glMultiTexCoord2sv         := { arg_types: ["uint", "short*"] }
static glMultiTexCoord3d          := { arg_types: ["uint", "double", "double", "double"] }
static glMultiTexCoord3dv         := { arg_types: ["uint", "double*"] }
static glMultiTexCoord3f          := { arg_types: ["uint", "float", "float", "float"] }
static glMultiTexCoord3fv         := { arg_types: ["uint", "float*"] }
static glMultiTexCoord3i          := { arg_types: ["uint", "int", "int", "int"] }
static glMultiTexCoord3iv         := { arg_types: ["uint", "int*"] }
static glMultiTexCoord3s          := { arg_types: ["uint", "short", "short", "short"] }
static glMultiTexCoord3sv         := { arg_types: ["uint", "short*"] }
static glMultiTexCoord4d          := { arg_types: ["uint", "double", "double", "double", "double"] }
static glMultiTexCoord4dv         := { arg_types: ["uint", "double*"] }
static glMultiTexCoord4f          := { arg_types: ["uint", "float", "float", "float", "float"] }
static glMultiTexCoord4fv         := { arg_types: ["uint", "float*"] }
static glMultiTexCoord4i          := { arg_types: ["uint", "int", "int", "int", "int"] }
static glMultiTexCoord4iv         := { arg_types: ["uint", "int*"] }
static glMultiTexCoord4s          := { arg_types: ["uint", "short", "short", "short", "short"] }
static glMultiTexCoord4sv         := { arg_types: ["uint", "short*"] }
static glLoadTransposeMatrixd     := { arg_types: ["double"] }
static glLoadTransposeMatrixf     := { arg_types: ["float"] }
static glMultTransposeMatrixd     := { arg_types: ["double"] }
static glMultTransposeMatrixf     := { arg_types: ["float"] }
static glSampleCoverage           := { arg_types: ["float", "uchar"] }
static glSamplePass               := { arg_types: ["uint"] }
