SwapBuffers                         ("uint")
wglAllocateMemoryNV                 ("int"," float"," float"," float")
wglAssociateImageBufferEventsI3D    ("uint"," uint*"," ptr"," DWORD*"," uint")
wglBeginFrameTrackingI3D            ()
wglBindDisplayColorTableEXT         ("ushort")
wglBindSwapBarrierNV                ("uint"," uint")
wglBindTexImageARB                  ("HPBUFFERARB"," int")
wglBindVideoCaptureDeviceNV         ("uint"," HVIDEOINPUTDEVICENV")
wglBindVideoDeviceNV                ("uint"," uint"," HVIDEOOUTPUTDEVICENV"," int*")
wglBindVideoImageNV                 ("HPVIDEODEV"," HPBUFFERARB"," int")
wglBlitContextFramebufferAMD        ("uint"," int"," int"," int"," int"," int"," int"," int"," int"," GLbitfield"," uint")
wglChoosePixelFormatARB             ("uint"," int*"," float*"," uint"," int*"," uint*")
wglChoosePixelFormatEXT             ("uint"," int*"," float*"," uint"," int*"," uint*")
wglCopyContext                      ("uint"," uint"," uint")
wglCopyImageSubDataNV               ("uint"," uint"," uint"," int"," int"," int"," int"," uint"," uint"," uint"," int"," int"," int"," int"," int"," int"," int")
wglCreateAffinityDCNV               ("HGPUNV*")
wglCreateAssociatedContextAMD       ("uint")
wglCreateAssociatedContextAttribsAMD("uint"," uint"," int*")
wglCreateBufferRegionARB            ("uint"," int"," uint")
wglCreateContext                    ("uint")
wglCreateContextAttribsARB          ("uint"," uint"," int*")
wglCreateDisplayColorTableEXT       ("ushort")
wglCreateImageBufferI3D             ("uint"," DWORD"," uint")
wglCreateLayerContext               ("uint"," int")
wglCreatePbufferARB                 ("uint"," int"," int"," int"," int*")
wglCreatePbufferEXT                 ("uint"," int"," int"," int"," int*")
wglDeleteAssociatedContextAMD       ("uint")
wglDeleteBufferRegionARB            ("uint")
wglDeleteContext                    ("uint")
wglDeleteDCNV                       ("uint")
wglDescribeLayerPlane               ("uint"," int"," int"," uint"," LPLAYERPLANEDESCRIPTOR")
wglDestroyDisplayColorTableEXT      ("ushort")
wglDestroyImageBufferI3D            ("uint"," ptr")
wglDestroyPbufferARB                ("HPBUFFERARB")
wglDestroyPbufferEXT                ("HPBUFFEREXT")
wglDisableFrameLockI3D              ()
wglDisableGenlockI3D                ("uint")
wglDXCloseDeviceNV                  ("uint")
wglDXLockObjectsNV                  ("uint"," int"," uint*")
wglDXObjectAccessNV                 ("uint"," uint")
wglDXOpenDeviceNV                   ("ptr")
wglDXRegisterObjectNV               ("uint"," ptr"," uint"," uint"," uint")
wglDXSetResourceShareHandleNV       ("ptr"," uint")
wglDXUnlockObjectsNV                ("uint"," int"," uint*")
wglDXUnregisterObjectNV             ("uint"," uint")
wglEnableFrameLockI3D               ()
wglEnableGenlockI3D                 ("uint")
wglEndFrameTrackingI3D              ()
wglEnumerateVideoCaptureDevicesNV   ("uint"," HVIDEOINPUTDEVICENV*")
wglEnumerateVideoDevicesNV          ("uint"," HVIDEOOUTPUTDEVICENV*")
wglEnumGpuDevicesNV                 ("HGPUNV"," uint"," PGPU_DEVICE")
wglEnumGpusFromAffinityDCNV         ("uint"," uint"," HGPUNV*")
wglEnumGpusNV                       ("uint"," HGPUNV*")
wglFreeMemoryNV                     ("ptr")
wglGenlockSampleRateI3D             ("uint"," uint")
wglGenlockSourceDelayI3D            ("uint"," uint")
wglGenlockSourceEdgeI3D             ("uint"," uint")
wglGenlockSourceI3D                 ("uint"," uint")
wglGetContextGPUIDAMD               ("uint")
wglGetCurrentAssociatedContextAMD   ()
wglGetCurrentContext                ("VOID")
wglGetCurrentDC                     ("VOID")
wglGetCurrentReadDCARB              ()
wglGetCurrentReadDCEXT              ()
wglGetDigitalVideoParametersI3D     ("uint"," int"," int*")
wglGetExtensionsStringARB           ("uint")
wglGetExtensionsStringEXT           ()
wglGetFrameUsageI3D                 ("float*")
wglGetGammaTableI3D                 ("uint"," int"," ushort*"," ushort*"," ushort*")
wglGetGammaTableParametersI3D       ("uint"," int"," int*")
wglGetGenlockSampleRateI3D          ("uint"," uint*")
wglGetGenlockSourceDelayI3D         ("uint"," uint*")
wglGetGenlockSourceEdgeI3D          ("uint"," uint*")
wglGetGenlockSourceI3D              ("uint"," uint*")
wglGetGPUIDsAMD                     ("uint"," uint*")
wglGetGPUInfoAMD                    ("uint"," int"," uint"," uint"," ptr")
wglGetLayerPaletteEntries           ("uint"," int"," int"," int"," COLORREF*")
wglGetMscRateOML                    ("uint"," int*"," int*")
wglGetPbufferDCARB                  ("HPBUFFERARB")
wglGetPbufferDCEXT                  ("HPBUFFEREXT")
wglGetPixelFormatAttribfvARB        ("uint"," int"," int"," uint"," int*"," float*")
wglGetPixelFormatAttribfvEXT        ("uint"," int"," int"," uint"," int*"," float*")
wglGetPixelFormatAttribivARB        ("uint"," int"," int"," uint"," int*"," int*")
wglGetPixelFormatAttribivEXT        ("uint"," int"," int"," uint"," int*"," int*")
wglGetProcAddress                   ("LPCSTR")
wglGetSwapIntervalEXT               ()
wglGetSyncValuesOML                 ("uint"," int64*"," int64*"," int64*")
wglGetVideoDeviceNV                 ("uint"," int"," HPVIDEODEV*")
wglGetVideoInfoNV                   ("HPVIDEODEV"," ulong*"," ulong*")
wglIsEnabledFrameLockI3D            ("BOOL*")
wglIsEnabledGenlockI3D              ("uint"," BOOL*")
wglJoinSwapGroupNV                  ("uint"," uint")
wglLoadDisplayColorTableEXT         ("ushort*"," uint")
wglLockVideoCaptureDeviceNV         ("uint"," HVIDEOINPUTDEVICENV")
wglMakeAssociatedContextCurrentAMD  ("uint")
wglMakeContextCurrentARB            ("uint"," uint"," uint")
wglMakeContextCurrentEXT            ("uint"," uint"," uint")
wglMakeCurrent                      ("uint"," uint")
wglQueryCurrentContextNV            ("int"," int*")
wglQueryFrameCountNV                ("uint"," uint*")
wglQueryFrameLockMasterI3D          ("BOOL*")
wglQueryFrameTrackingI3D            ("DWORD*"," DWORD*"," float*")
wglQueryGenlockMaxSourceDelayI3D    ("uint"," uint*"," uint*")
wglQueryMaxSwapGroupsNV             ("uint"," uint*"," uint*")
wglQueryPbufferARB                  ("HPBUFFERARB"," int"," int*")
wglQueryPbufferEXT                  ("HPBUFFEREXT"," int"," int*")
wglQuerySwapGroupNV                 ("uint"," uint*"," uint*")
wglQueryVideoCaptureDeviceNV        ("uint"," HVIDEOINPUTDEVICENV"," int"," int*")
wglRealizeLayerPalette              ("uint"," int"," BOOL")
wglReleaseImageBufferEventsI3D      ("uint"," LPptr"," uint")
wglReleasePbufferDCARB              ("HPBUFFERARB"," uint")
wglReleasePbufferDCEXT              ("HPBUFFEREXT"," uint")
wglReleaseTexImageARB               ("HPBUFFERARB"," int")
wglReleaseVideoCaptureDeviceNV      ("uint"," HVIDEOINPUTDEVICENV")
wglReleaseVideoDeviceNV             ("HPVIDEODEV")
wglReleaseVideoImageNV              ("HPBUFFERARB"," int")
wglResetFrameCountNV                ("uint")
wglRestoreBufferRegionARB           ("uint"," int"," int"," int"," int"," int"," int")
wglSaveBufferRegionARB              ("uint"," int"," int"," int"," int")
wglSendPbufferToVideoNV             ("HPBUFFERARB"," int"," ulong*"," BOOL")
wglSetDigitalVideoParametersI3D     ("uint"," int"," int*")
wglSetGammaTableI3D                 ("uint"," int"," ushort*"," ushort*"," ushort*")
wglSetGammaTableParametersI3D       ("uint"," int"," int*")
wglSetLayerPaletteEntries           ("uint"," int"," int"," int"," CONST COLORREF *")
wglSetPbufferAttribARB              ("HPBUFFERARB"," int*")
wglSetStereoEmitterState3DL         ("uint"," uint")
wglShareLists                       ("uint"," uint")
wglSwapBuffersMscOML                ("uint"," int64"," int64"," int64")
wglSwapIntervalEXT                  ("int")
wglSwapLayerBuffers                 ("uint"," uint")
wglSwapLayerBuffersMscOML           ("uint"," int"," int64"," int64"," int64")
wglSwapMultipleBuffers              ("uint"," CONST WGLSWAP*")
wglUseFontBitmaps                   ("uint"," DWORD"," DWORD"," DWORD")
wglUseFontOutlines                  ("uint"," DWORD"," DWORD"," DWORD"," FLOAT"," FLOAT"," int"," LPGLYPHMETRICSFLOAT")
wglWaitForMscOML                    ("uint"," int64"," int64"," int64"," int64*"," int64*"," int64*")
wglWaitForSbcOML                    ("uint"," int64"," int64*"," int64*"," int64*")